#!/usr/bin/env python3
"""Build every generated asset for the IKEA LACK table prototype.

Local prototype only — see README.md (this whole directory only exists on
the local/ikea-furniture-prototype branch). Consolidates what used to be
five separate scripts (rescale_robotiq_meshes.py, generate_robotiq_urdf.sh,
generate_hole_peg_meshes.py, generate_urdf_srdf.py, merge_ur10_robotiq.py —
removed) into one, since they form a single linear pipeline with no
independent reuse: each stage's output is the next stage's only input, and
none of them were ever run standalone against a different scene. A sixth,
rescale_ikea_meshes.py, was dropped entirely rather than merged — its
output (assets/meshes_scaled/{table,leg1..4}.stl, the real vendored IKEA
mesh rescaled) was never consumed by anything: generate_urdf_srdf's visual
geometry moved to generate_hole_peg_meshes' fresh box-with-holes/peg
meshes instead (see that stage's own docstring below for why), leaving
the rescaled real-product meshes orphaned.

PIPELINE ORDER (default: every stage, in order; --only for just one)
--------------------------------------------------------------------
  1. rescale-robotiq-meshes
     Robotiq DAE/STL -> assets/robotiq_2f85/meshes_scaled/
  2. robotiq-urdf
     xacro -> assets/robotiq_2f85/urdf/robotiq_2f85_generated.urdf
  3. hole-peg-meshes
     trimesh boolean ops
     -> assets/meshes_generated/{table_with_holes,leg_with_peg}.stl
  4. urdf-srdf
     table.{urdf,srdf}, leg{1..4}.{urdf,srdf} -> generated/
  5. merge-arm
     UR10 + Robotiq + pedestal -> generated/ur10_robotiq{,_right}.urdf
  6. container-variant
     host-path -> container-path twins of stage 5's output (see below)

Stages 1-2 only need re-running if the vendored Robotiq xacro/mesh sources
change. Stages 3-4 are what actually get edited/re-run during scene
iteration (mesh dimensions, socket positions, handle geometry). Stage 5
only needs re-running if the arm/gripper mount or pedestal changes.

ground.urdf / workbench.urdf in generated/ have no corresponding stage
here — they're plain hand-authored static geometry (no meshes, pure
primitive boxes), never generated by any script, committed as-is.

CONTAINER VS. HOST PATHS — read before running stage 5 or 6
--------------------------------------------------------------
pyhpp only imports inside the hpp-agimus-arm64 container (see
debug_view_frames.py's docstring), which mounts this repo at
/home/thanhndv212/devel/hpp/src/long_tamp — NOT at this host's own path
(/Users/thanhndv212/Develop/agimus-ws/long-tamp). Every mesh <filename> and
every top-level URDF/SRDF path baked in by this script is HERE-relative
(``Path(__file__).parent``), so whichever environment you *run this
script from* determines which paths end up in generated/ — there is no
detection or translation of that automatically.

Stages 3-4's output (table/leg URDFs) currently sits with container-correct
paths because that's where this script was last run from — if you edit and
re-run stage 4 from the host, its output reverts to host paths and won't
resolve when a task script tries to load it inside the container. Simplest
fix: re-run from inside the container (matches how every fix during this
prototype's actual debugging session was applied — see docker exec
examples in this repo's own session history / task_assemble_table.py).

Stage 5's output (the two arm URDFs) additionally gets an explicit
``.container.urdf`` *twin* (stage 6, --containerize) — a older, pre-
existing naming convention this script preserves rather than invents:
config/ikea_table_config.yaml's paths.robot entries reference
ur10_robotiq(.container)?.urdf specifically. Table/leg/ground/workbench
URDFs have no such twin-naming convention; they're just regenerated
in-place per environment.
"""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent
GEN_DIR = HERE / "generated"

CONTAINER_REPO_ROOT = "/home/thanhndv212/devel/hpp/src/long_tamp"
# NOT derived from HERE — see stage 6's own docstring for why this has to
# be a fixed literal rather than "wherever this script currently runs".
HOST_REPO_ROOT = "/Users/thanhndv212/Develop/agimus-ws/long-tamp"


# =============================================================================
# Stage 1 — rescale Robotiq meshes (bake the 0.001 scale into vertices)
# =============================================================================
#
# The vendored xacro sources declare <mesh scale="0.001 0.001 0.001"/>
# (their DAE/STL files are authored in millimeters). pyhpp_viser's
# Viewer._update_geometry_frames() has a known bug (see
# script/twin/assets/pokeball_bimanual.urdf's header comment): rendered
# position = world_translation * meshScale, when meshScale should only
# scale local vertices. Any non-unit <mesh scale> collapses that geometry
# down near the world origin regardless of its real joint pose — confirmed
# live: Robotiq's parts (scale 0.001) all rendered within ~1mm of origin
# while UR10's own parts (scale 1, unaffected) rendered correctly.
#
# Fix (same one script/twin's pokeball example already applied):
# eliminate the non-unit scale by rescaling the mesh data itself via
# trimesh, so the URDF can reference it with no <mesh scale> attribute at
# all — same convention UR10's own meshes already use. The vendored xacro
# sources (assets/robotiq_2f85/urdf/*.xacro) already reference
# meshes_scaled/ paths directly with no <mesh scale> — that path-and-scale
# edit was a one-time hand patch, not something this stage repeats; this
# stage only produces the mesh files those paths expect to find.

ROBOTIQ_MESH_DIR = HERE / "assets" / "robotiq_2f85" / "meshes"
ROBOTIQ_MESH_SCALED_DIR = HERE / "assets" / "robotiq_2f85" / "meshes_scaled"
ROBOTIQ_MESH_SCALE = 0.001

# robotiq_arg2f_base_link.stl is the one file the source xacro references
# with NO <mesh scale> — already authored in meters, unlike every other
# Robotiq mesh here (all in millimeters). Must not be rescaled again.
ROBOTIQ_ALREADY_METERS = {"robotiq_arg2f_base_link.stl"}


def rescale_robotiq_meshes() -> None:
    import trimesh

    for sub in ("collision", "visual"):
        for src in sorted((ROBOTIQ_MESH_DIR / sub).iterdir()):
            dst = ROBOTIQ_MESH_SCALED_DIR / sub / src.name
            dst.parent.mkdir(parents=True, exist_ok=True)
            if src.name in ROBOTIQ_ALREADY_METERS:
                dst.write_bytes(src.read_bytes())
                print(f"copied (already meters) {src.name}")
                continue
            mesh = trimesh.load(src, force="mesh")
            mesh.apply_scale(ROBOTIQ_MESH_SCALE)
            mesh.export(dst)
            print(f"rescaled {src.name} (x{ROBOTIQ_MESH_SCALE}) -> "
                  f"{dst.relative_to(HERE.parent.parent)}")


# =============================================================================
# Stage 2 — xacro -> robotiq_2f85_generated.urdf
# =============================================================================
#
# The upstream xacro files (assets/robotiq_2f85/urdf/*.xacro, vendored
# as-is from ros-industrial/robotiq's robotiq_2f_85_gripper_visualization,
# BSD-2-Clause) use ROS-only substitutions this standalone `pip install
# xacro` can't resolve without a real ROS install:
#   - `$(find robotiq_2f_85_gripper_visualization)` (needs ament_index /
#     rospkg) — already patched in-place to this vendored directory's
#     absolute path in robotiq_arg2f_85_model.xacro / _macro.xacro.
#   - `package://robotiq_2f_85_gripper_visualization/...` mesh URIs — same
#     patch, in robotiq_arg2f_85_model_macro.xacro AND robotiq_arg2f.xacro
#     (a separate xacro:include'd from inside the macro file, easy to
#     miss).
# Both patches are already applied to the committed xacro sources — this
# stage only re-runs the xacro expansion, it doesn't re-patch anything.
#
# Requires: pip install xacro (a one-off local conversion tool, not a
# long_tamp dependency).

ROBOTIQ_XACRO_DIR = HERE / "assets" / "robotiq_2f85" / "urdf"
ROBOTIQ_XACRO_SRC = "robotiq_arg2f_85_model.xacro"
ROBOTIQ_URDF_OUT = "robotiq_2f85_generated.urdf"


def generate_robotiq_urdf() -> None:
    import xacro

    out_path = ROBOTIQ_XACRO_DIR / ROBOTIQ_URDF_OUT
    prev_argv = sys.argv
    prev_cwd = Path.cwd()
    try:
        sys.argv = ["xacro", ROBOTIQ_XACRO_SRC, "-o", ROBOTIQ_URDF_OUT]
        import os
        os.chdir(ROBOTIQ_XACRO_DIR)
        xacro.main()
    finally:
        sys.argv = prev_argv
        import os
        os.chdir(prev_cwd)

    print(f"wrote {out_path.relative_to(HERE.parent.parent)}")
    content = out_path.read_text()
    if "find" in content or "package://" in content:
        raise RuntimeError(
            "unresolved ROS substitution remains in "
            f"{ROBOTIQ_URDF_OUT} — check for a new xacro:include this "
            "stage's patching doesn't cover yet."
        )


# =============================================================================
# Stage 3 — box-with-holes table mesh + box-with-peg leg mesh (trimesh)
# =============================================================================
#
# Fresh, programmatically-generated geometry (box boolean-differenced/
# unioned with cylinders via trimesh) — not derived from or copying the
# real vendored IKEA STL meshes in any way, just built from the same box
# dimensions/socket positions also used for collision (LEG_HALF_EXTENT /
# TABLE_HALF_EXTENT / LEG_SOCKET_XY below, shared with stage 4).
#
# Visual only. Collision stays the plain convex box in stage 4 — HPP-FCL's
# narrow-phase collision checking wants convex shapes, and a
# box-with-holes is non-convex; visual/collision geometry not matching
# exactly is standard practice (detailed visual mesh, simple convex
# collision proxy), same pattern already used for e.g. UR10's own meshes
# (separate visual .dae / collision .stl, different tessellation).
#
# Requires a trimesh boolean backend (this repo's HPP env didn't ship one
# by default): pip install manifold3d.

MESH_GENERATED_DIR = HERE / "assets" / "meshes_generated"

TABLE_HALF_EXTENT = (0.32, 0.12, 0.02)
LEG_HALF_EXTENT = (0.015, 0.015, 0.13125)
# Table-local XY positions of the 4 leg sockets (underside), from the
# vendored reference MJCF's table-leg conn_site1..4
# (assets/reference_table_lack_0825.mjcf.xml, from clvrai/furniture).
LEG_SOCKET_XY = [
    (-0.305, -0.095),
    (-0.305, 0.095),
    (0.305, -0.095),
    (0.305, 0.095),
]

HOLE_RADIUS = 0.012
HOLE_DEPTH = 0.015  # blind hole, out of the table's 0.04 total thickness
PEG_RADIUS = 0.010
PEG_HEIGHT = 0.020  # protrudes above the leg's top face


def _build_table_mesh():
    import trimesh

    tx, ty, tz = TABLE_HALF_EXTENT
    box = trimesh.creation.box(extents=(2 * tx, 2 * ty, 2 * tz))

    cutters = []
    for cx, cy in LEG_SOCKET_XY:
        cyl = trimesh.creation.cylinder(radius=HOLE_RADIUS, height=0.06)
        # Cylinder is centered at its own origin; place it so it starts
        # at the table's TOP face (+tz) and reaches HOLE_DEPTH down into
        # the material, extending further above +tz — the portion above
        # +tz has no box material to subtract, so only the overlapping
        # part actually carves in. Holes on top (not the underside) so
        # they're reachable by an arm approaching from above once the
        # table sits flat on a workbench — a bottom-face hole would be
        # pressed against the workbench surface, inaccessible.
        cyl.apply_translation((cx, cy, tz - HOLE_DEPTH + 0.03))
        cutters.append(cyl)

    result = trimesh.boolean.difference([box, *cutters])
    if not result.is_watertight:
        raise RuntimeError("table-with-holes mesh is not watertight")
    return result


def _build_leg_mesh():
    import trimesh

    lx, ly, lz = LEG_HALF_EXTENT
    box = trimesh.creation.box(extents=(2 * lx, 2 * ly, 2 * lz))
    peg = trimesh.creation.cylinder(radius=PEG_RADIUS, height=PEG_HEIGHT)
    peg.apply_translation((0, 0, lz + PEG_HEIGHT / 2))
    result = trimesh.boolean.union([box, peg])
    if not result.is_watertight:
        raise RuntimeError("leg-with-peg mesh is not watertight")
    return result


def generate_hole_peg_meshes() -> None:
    MESH_GENERATED_DIR.mkdir(exist_ok=True)

    table = _build_table_mesh()
    table_path = MESH_GENERATED_DIR / "table_with_holes.stl"
    table.export(table_path)
    print(f"wrote {table_path.relative_to(HERE.parent.parent)} "
          f"({len(table.vertices)} vertices, "
          f"watertight={table.is_watertight})")

    leg = _build_leg_mesh()
    leg_path = MESH_GENERATED_DIR / "leg_with_peg.stl"
    leg.export(leg_path)
    print(f"wrote {leg_path.relative_to(HERE.parent.parent)} "
          f"({len(leg.vertices)} vertices, watertight={leg.is_watertight})")


# =============================================================================
# Stage 4 — table.{urdf,srdf} / leg{1..4}.{urdf,srdf}
# =============================================================================
#
# All dimensions and connection-site positions are read directly off the
# vendored reference MJCF (assets/reference_table_lack_0825.mjcf.xml, from
# clvrai/furniture), not guessed: MJCF <geom size="..."> for a box is
# *half*-extents, so URDF <box size="..."> (full extents) is 2x each value
# here (see TABLE_HALF_EXTENT / LEG_HALF_EXTENT above, shared with stage 3).
#
# Each part is a free-flying object (single base_link, no internal
# joints) — matching script/twin/assets/pokeball_bimanual.urdf's pattern.
# Assembly (leg-into-table) is modeled as a placement <contact> pair, not
# a <handle> pair: h_RS1_CON0..3-style paired handles (see
# agimus_spacelab's RS1.srdf) are for a dedicated screwdriver *tool*
# docking at a fastener point, which this example doesn't have — a single
# generic Robotiq gripper does all the grasping, and the leg-into-table
# mate is a plain placement constraint, the same mechanism the ball uses
# to rest on the ground.
#
# Visual geometry is stage 3's output (box-with-holes / box-with-peg), NOT
# the real vendored IKEA STL meshes — those bake in the actual product's
# screw-hole/dowel-hole surface detail, which rendered visibly and wasn't
# wanted even for local prototyping. Collision stays the plain convex box
# — HPP-FCL's narrow-phase checking wants convex shapes, and the hole/peg
# mesh isn't.

LEGS = ["leg1", "leg2", "leg3", "leg4"]

_URDF_TEMPLATE = """<?xml version="1.0"?>
<!--
  GENERATED by build_assets.py (urdf-srdf stage) — local
  prototype only, see README.md. Box dimensions read from the vendored
  reference MJCF (LACK table, originally from clvrai/furniture, itself
  real IKEA product geometry).

  Visual geometry is {visual_mesh_basename} — a fresh, programmatically
  generated box-with-holes/box-with-peg mesh (see the hole-peg-meshes
  stage; NOT the real vendored IKEA STL, which bakes in the actual
  product's screw-hole surface detail and wasn't wanted even for local
  prototyping). Collision stays the plain convex box below — HPP-FCL's
  narrow-phase checking wants convex shapes, and the hole/peg mesh isn't;
  visual/collision not matching exactly is standard practice (detailed
  visual mesh, simple convex collision proxy).
-->
<robot name="{name}">
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{visual_mesh_path}"/>
      </geometry>
      <material name="light_wood">
        <color rgba="0.82 0.71 0.55 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="{box_size}"/>
      </geometry>
    </collision>
  </link>
</robot>
"""

_SRDF_LEG_TEMPLATE = """<?xml version="1.0"?>
<!-- GENERATED — see build_assets.py. Local prototype only. -->
<robot name="{name}">
  <!-- Grasp point: leg center, gripper approaches from the side — a
       parallel jaw closing across the leg's 0.03x0.03 cross-section.

       approaching_direction is "-1 0 0", not "+1 0 0": HPP's
       Handle::createPreGrasp offsets the pregrasp target by
       +clearance*approaching_direction (in the handle's own, i.e. this
       link's, local frame). With the legs lying flat on the workbench
       (LEG_LIE_FLAT_QUAT in debug_view_frames.py, a 90deg rotation about
       world Y), local +X maps to world -Z — so a "+1 0 0" direction here
       computed a pregrasp target 2mm *below* the workbench surface,
       confirmed empirically (query the loaded Device: handle world
       z=0.418, computed pregrasp z=0.398 vs. workbench top z=0.400) — a
       permanently unreachable, always-in-collision target no amount of
       retrying could ever satisfy, which is exactly what
       task_assemble_table.py's first real planning run hit (100% failure
       across every attempt/rerun, always workbench- or ground-collision).
       "-1 0 0" gives world +Z (pregrasp z=0.438, above the leg) instead —
       verified the same way. -->
  <handle name="handle" clearance="0.02" approaching_direction="-1 0 0">
    <position xyz="0 0 0" xyzw="0 0 0 1"/>
    <link name="base_link"/>
  </handle>
  <!-- Placement contact: the leg's top face, mated against the matching
       socket contact on the table (see table.srdf) — same mechanism as
       script/twin/assets/pokeball_bimanual.srdf's "bottom" contact.
       Bare name, like that precedent's "bottom" and this file's own
       "handle" above — pyhpp's urdf.loadModel(name=...) prefixes every
       handle/contact with the object's load name itself (confirmed live:
       a name of "{name}/top" here produced a double-prefixed
       "{name}/{name}/top" at runtime, "No handle/contact with name
       {name}/top" from HPP). -->
  <contact name="top">
    <link name="base_link"/>
    <point>
       {hx} {hy} {top_z}
      -{hx} {hy} {top_z}
      -{hx} -{hy} {top_z}
       {hx} -{hy} {top_z}
    </point>
    <shape>
      4 0 1 2 3
    </shape>
  </contact>
</robot>
"""

_SRDF_TABLE_TEMPLATE = """<?xml version="1.0"?>
<!-- GENERATED — see build_assets.py. Local prototype only. -->
<robot name="table">
  <!-- Grasp point: top face center, in case a phase needs to hold the
       table steady while a leg is attached. Tentative, same caveat as
       the leg handles. -->
  <handle name="handle" clearance="0.02" approaching_direction="0 0 1">
    <position xyz="0 0 0" xyzw="0 0 0 1"/>
    <link name="base_link"/>
  </handle>
{contacts}</robot>
"""

# Bare names ("handle" above, "socketN" below) — pyhpp's urdf.loadModel
# prefixes every handle/contact with the object's own load name, so a
# name already containing that prefix double-prefixes at runtime; see
# _SRDF_LEG_TEMPLATE's comment for the live error this produced.
_SOCKET_CONTACT_TEMPLATE = """  <!-- Socket {i}: mates with legN/top, at table-local ({cx}, {cy}) -->
  <contact name="socket{i}">
    <link name="base_link"/>
    <point>
       {p0x} {p0y} {sock_z}
       {p1x} {p1y} {sock_z}
       {p2x} {p2y} {sock_z}
       {p3x} {p3y} {sock_z}
    </point>
    <shape>
      4 0 1 2 3
    </shape>
  </contact>
"""


def _write(path: Path, content: str) -> None:
    path.write_text(content)
    print(f"wrote {path.relative_to(HERE.parent.parent)}")


def generate_urdf_srdf() -> None:
    GEN_DIR.mkdir(exist_ok=True)

    leg_peg_mesh_path = str(
        (MESH_GENERATED_DIR / "leg_with_peg.stl").resolve()
    )
    table_holes_mesh_path = str(
        (MESH_GENERATED_DIR / "table_with_holes.stl").resolve()
    )

    lx, ly, lz = LEG_HALF_EXTENT
    leg_box_size = f"{2*lx} {2*ly} {2*lz}"
    leg_mass = "0.3"

    for name in LEGS:
        urdf = _URDF_TEMPLATE.format(
            name=name,
            mass=leg_mass,
            visual_mesh_basename="leg_with_peg.stl",
            visual_mesh_path=leg_peg_mesh_path,
            box_size=leg_box_size,
        )
        _write(GEN_DIR / f"{name}.urdf", urdf)

        srdf = _SRDF_LEG_TEMPLATE.format(
            name=name, hx=lx, hy=ly, top_z=round(lz, 6)
        )
        _write(GEN_DIR / f"{name}.srdf", srdf)

    tx, ty, tz = TABLE_HALF_EXTENT
    table_box_size = f"{2*tx} {2*ty} {2*tz}"
    table_urdf = _URDF_TEMPLATE.format(
        name="table",
        mass="2.0",
        visual_mesh_basename="table_with_holes.stl",
        visual_mesh_path=table_holes_mesh_path,
        box_size=table_box_size,
    )
    _write(GEN_DIR / "table.urdf", table_urdf)

    # Top face (+tz), not bottom (-tz) — matches the hole-peg-meshes
    # stage's holes, which are on the top surface so they're reachable by
    # an arm approaching from above (a bottom-face hole is pressed
    # against the workbench once the table sits flat, inaccessible).
    sock_z = round(tz, 6)
    contact_blocks = []
    for i, (cx, cy) in enumerate(LEG_SOCKET_XY, start=1):
        corners = [(cx + sx, cy + sy) for sx in (lx, -lx) for sy in (ly, -ly)]
        contact_blocks.append(
            _SOCKET_CONTACT_TEMPLATE.format(
                i=i,
                cx=cx,
                cy=cy,
                sock_z=sock_z,
                p0x=corners[0][0], p0y=corners[0][1],
                p1x=corners[1][0], p1y=corners[1][1],
                p2x=corners[2][0], p2y=corners[2][1],
                p3x=corners[3][0], p3y=corners[3][1],
            )
        )
    table_srdf = _SRDF_TABLE_TEMPLATE.format(contacts="".join(contact_blocks))
    _write(GEN_DIR / "table.srdf", table_srdf)


# =============================================================================
# Stage 5 — merge UR10 + Robotiq 2F-85 (+ pedestal) into one combined arm
# =============================================================================
#
# Neither source repo ships a combined description (they're separate ROS
# packages, never composed upstream), so this stitches them: takes every
# <link>/<joint> from both generated URDFs, adds one new fixed joint
# mounting the gripper's root link (robotiq_arg2f_base_link) onto the
# arm's tool0 frame.
#
# Mount offset (xyz/rpy on the new fixed joint) — identity — and the TCP
# frame's 0.15m z-offset were both visually verified in viser
# (debug_view_frames.py): the gripper renders flush and correctly-
# oriented on tool0, arm fully visible.
#
# Generates TWO files: ur10_robotiq.urdf (identity world placement, for
# ur10_left) and ur10_robotiq_right.urdf (world offset baked in via an
# outer "world_mount" fixed link, for ur10_right). The offset is baked
# into the URDF itself rather than applied via
# PyHPPBackend.load_robot(pose=...) / Device.setRobotRootPosition() after
# loading — a real pyhpp_viser bug: that post-load repositioning isn't
# reflected in *static* (fixed-to-universe) geometry rendering:
# ur10_right's pedestal rendered at ur10_left's position (both cached
# [0,0,0.15]) even though the real FK/model data was already correct
# (confirmed via direct Pinocchio queries before concluding this was a
# viewer bug, not a modeling one) — only geometry driven by a real moving
# joint reflected the offset correctly. Baking the offset into the URDF's
# own static structure instead sidesteps that code path entirely.

UR10_URDF = HERE / "assets" / "ur10" / "ur10_robot_generated.urdf"
ROBOTIQ_URDF = ROBOTIQ_XACRO_DIR / ROBOTIQ_URDF_OUT

GRIPPER_ROOT_LINK = "robotiq_arg2f_base_link"
ARM_MOUNT_FRAME = "tool0"

# Pedestal: a rigid part of this same URDF (fixed joint onto UR10's own
# root link, "world"), not a separately-positioned environment object —
# per live feedback that two independently-placed objects read as a gap
# rather than one attached assembly. 0.3x0.3m footprint.
#
# Height 0.5m (not 0.3m, which this was briefly lowered to and then
# raised back from, both times per live feedback): at 0.3m the shoulder
# (z=0.3) sat BELOW workbench.urdf's top (z=0.40, near edge only 0.25m
# from the arm base at x=0), so any reach onto the surface had to thread
# up and over the arm's own low mount with almost no clearance — real
# planning runs kept hitting "Collision between object
# ur10_left/forearm_link_0 and workbench/workbench_base_0" reaching leg1
# on top of it. A pinocchio DLS-IK check confirmed the pregrasp target
# itself was easily reachable in isolation (300/300 random restarts
# converged), so this was a real reach-geometry conflict with the
# workbench layout, not a target/orientation bug (that was a separate,
# already-fixed issue — see the urdf-srdf stage's approaching_direction
# comment).
PEDESTAL_LINK = "pedestal"
PEDESTAL_HEIGHT = 0.5
UR10_ROOT_LINK = "world"

# Mount transform — identity, visually verified in viser. See docstring.
MOUNT_XYZ = "0 0 0"
MOUNT_RPY = "0 0 0"

# TCP frame: base_link's own +Z is the fingers' approach direction
# (verified from the joint chain: finger_joint at z=0.0549, +
# left_inner_finger_joint at z=0.0471 more = ~0.102m to the inner-finger
# pivot; fingertip contact is further out). 0.15m is a published-typical
# 2F-85 TCP estimate, visually verified (arm+gripper render correctly in
# viser) but not measured against this exact mesh — fine for
# prototyping, revisit before anything precision-sensitive (e.g. actual
# grasp-pose tuning) depends on it.
TCP_LINK = "gripper_tcp"
TCP_Z = "0.15"

WORLD_MOUNT_LINK = "world_mount"
# ur10_right's world placement — 1.5m along X, rotated 180deg about Z to
# face back toward ur10_left. Matches debug_view_frames.py's layout.
RIGHT_ARM_XYZ = "1.5 0 0"
RIGHT_ARM_RPY = "0 0 3.141592653589793"


def _build_arm(world_xyz: str | None, world_rpy: str | None) -> ET.Element:
    ur10_tree = ET.parse(UR10_URDF)
    ur10_root = ur10_tree.getroot()

    robotiq_tree = ET.parse(ROBOTIQ_URDF)
    robotiq_root = robotiq_tree.getroot()

    combined = ET.Element("robot", {"name": "ur10_robotiq"})
    combined.append(
        ET.Comment(
            " GENERATED by build_assets.py (merge-arm stage) — "
            "local prototype only. UR10 (Gepetto/example-robot-data, "
            "BSD-3-Clause) + Robotiq 2F-85 (ros-industrial/robotiq, "
            "BSD-2-Clause), stitched at tool0. Mount offset + TCP frame "
            "visually verified in viser — see module docstring. "
        )
    )

    for child in ur10_root:
        if child.tag in ("link", "joint"):
            combined.append(child)
    for child in robotiq_root:
        if child.tag in ("link", "joint"):
            combined.append(child)

    pedestal_link = ET.Element("link", {"name": PEDESTAL_LINK})
    visual = ET.SubElement(pedestal_link, "visual")
    ET.SubElement(visual, "origin", {"xyz": f"0 0 {PEDESTAL_HEIGHT / 2}"})
    geom = ET.SubElement(visual, "geometry")
    ET.SubElement(geom, "box", {"size": f"0.3 0.3 {PEDESTAL_HEIGHT}"})
    material = ET.SubElement(visual, "material", {"name": "DarkGray"})
    ET.SubElement(material, "color", {"rgba": "0.3 0.3 0.3 1.0"})
    collision = ET.SubElement(pedestal_link, "collision")
    ET.SubElement(
        collision, "origin", {"xyz": f"0 0 {PEDESTAL_HEIGHT / 2}"}
    )
    geom = ET.SubElement(collision, "geometry")
    ET.SubElement(geom, "box", {"size": f"0.3 0.3 {PEDESTAL_HEIGHT}"})
    combined.append(pedestal_link)

    pedestal_joint = ET.Element(
        "joint", {"name": "pedestal_to_arm", "type": "fixed"}
    )
    ET.SubElement(
        pedestal_joint,
        "origin",
        {"xyz": f"0 0 {PEDESTAL_HEIGHT}", "rpy": "0 0 0"},
    )
    ET.SubElement(pedestal_joint, "parent", {"link": PEDESTAL_LINK})
    ET.SubElement(pedestal_joint, "child", {"link": UR10_ROOT_LINK})
    combined.append(pedestal_joint)

    mount_joint = ET.Element(
        "joint", {"name": "tool0_to_gripper", "type": "fixed"}
    )
    ET.SubElement(mount_joint, "origin", {"xyz": MOUNT_XYZ, "rpy": MOUNT_RPY})
    ET.SubElement(mount_joint, "parent", {"link": ARM_MOUNT_FRAME})
    ET.SubElement(mount_joint, "child", {"link": GRIPPER_ROOT_LINK})
    combined.append(mount_joint)

    tcp_link = ET.Element("link", {"name": TCP_LINK})
    combined.append(tcp_link)
    tcp_joint = ET.Element(
        "joint", {"name": "gripper_to_tcp", "type": "fixed"}
    )
    ET.SubElement(tcp_joint, "origin", {"xyz": f"0 0 {TCP_Z}", "rpy": "0 0 0"})
    ET.SubElement(tcp_joint, "parent", {"link": GRIPPER_ROOT_LINK})
    ET.SubElement(tcp_joint, "child", {"link": TCP_LINK})
    combined.append(tcp_joint)

    if world_xyz is not None:
        world_mount_link = ET.Element("link", {"name": WORLD_MOUNT_LINK})
        combined.append(world_mount_link)
        world_mount_joint = ET.Element(
            "joint", {"name": "world_mount_to_pedestal", "type": "fixed"}
        )
        ET.SubElement(
            world_mount_joint, "origin", {"xyz": world_xyz, "rpy": world_rpy}
        )
        ET.SubElement(world_mount_joint, "parent", {"link": WORLD_MOUNT_LINK})
        ET.SubElement(world_mount_joint, "child", {"link": PEDESTAL_LINK})
        combined.append(world_mount_joint)

    return combined


def _write_xml(root: ET.Element, out_path: Path) -> None:
    out_path.parent.mkdir(exist_ok=True)
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(
        out_path, xml_declaration=True, encoding="unicode"
    )
    print(f"wrote {out_path.relative_to(HERE.parent.parent)}")


def merge_arm() -> None:
    _write_xml(_build_arm(None, None), GEN_DIR / "ur10_robotiq.urdf")
    _write_xml(
        _build_arm(RIGHT_ARM_XYZ, RIGHT_ARM_RPY),
        GEN_DIR / "ur10_robotiq_right.urdf",
    )


# =============================================================================
# Stage 6 — .container.urdf twins of stage 5's output
# =============================================================================
#
# Codifies what was, during this prototype's actual debugging session, a
# manual `sed` pass: rewrite every mesh <filename> whose prefix is
# HOST_REPO_ROOT to CONTAINER_REPO_ROOT instead, so the result is loadable
# from inside the hpp-agimus-arm64 container.
#
# HOST_REPO_ROOT is a fixed literal, NOT derived from HERE (tried that
# first — wrong): merge-arm's mesh <filename> paths are inherited
# verbatim from assets/ur10/ur10_robot_generated.urdf and
# assets/robotiq_2f85/urdf/robotiq_2f85_generated.urdf, neither of which
# this pipeline generates — the first is a pre-existing vendored xacro
# export (same category as generated/ground.urdf, no live generator at
# all), the second's *source xacro* has the host path hand-patched
# directly into it (stage 2's docstring), not resolved dynamically. Both
# carry HOST_REPO_ROOT regardless of where merge-arm itself is run from
# — confirmed live: running merge-arm from inside the container still
# produced host-absolute mesh paths, because HERE-based substitution
# only affects paths *this script* constructs itself (stages 3/4's own
# mesh references), not ones copied in from these two upstream files.

def write_container_variant() -> None:
    for name in ("ur10_robotiq.urdf", "ur10_robotiq_right.urdf"):
        src = GEN_DIR / name
        dst = GEN_DIR / name.replace(".urdf", ".container.urdf")
        text = src.read_text()
        text = re.sub(re.escape(HOST_REPO_ROOT), CONTAINER_REPO_ROOT, text)
        dst.write_text(text)
        n_paths = text.count(CONTAINER_REPO_ROOT)
        print(f"wrote {dst.relative_to(HERE.parent.parent)} "
              f"({n_paths} container-absolute mesh path(s))")


# =============================================================================
# CLI
# =============================================================================

STAGES = {
    "rescale-robotiq-meshes": rescale_robotiq_meshes,
    "robotiq-urdf": generate_robotiq_urdf,
    "hole-peg-meshes": generate_hole_peg_meshes,
    "urdf-srdf": generate_urdf_srdf,
    "merge-arm": merge_arm,
    "container-variant": write_container_variant,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--only",
        choices=list(STAGES.keys()),
        action="append",
        help="Run only this stage (repeatable). Default: run every stage in "
        "pipeline order.",
    )
    args = parser.parse_args()

    stages = args.only if args.only else list(STAGES.keys())
    for stage in stages:
        print(f"=== {stage} ===")
        STAGES[stage]()
    return 0


if __name__ == "__main__":
    sys.exit(main())
