#!/usr/bin/env python3
"""Generate URDF+SRDF for the IKEA LACK table prototype (table + 4 legs).

Local prototype only — see ../README.md. All dimensions and connection-site
positions below are read directly off the vendored reference MJCF
(assets/reference_table_lack_0825.mjcf.xml, from clvrai/furniture), not
guessed: MJCF <geom size="..."> for a box is *half*-extents, so URDF
<box size="..."> (full extents) is 2x each value here.

Each part is a free-flying object (single base_link, no internal joints) —
matching script/twin/assets/pokeball_bimanual.urdf's pattern. Assembly
(leg-into-table) is modeled as a placement <contact> pair, not a <handle>
pair: h_RS1_CON0..3-style paired handles (see agimus_spacelab's RS1.srdf)
are for a dedicated screwdriver *tool* docking at a fastener point, which
this example doesn't have — a single generic Robotiq gripper does all the
grasping, and the leg-into-table mate is a plain placement constraint, the
same mechanism the ball uses to rest on the ground.

Visual geometry references generate_hole_peg_meshes.py's output — a
box-with-holes table mesh and a box-with-peg leg mesh — not the real
vendored STL meshes. Those bake in the actual IKEA LACK table's real
screw-hole/dowel-hole surface detail, which rendered visibly and wasn't
wanted even for local prototyping; the generated meshes give a genuine
recessed hole / protruding peg instead, built fresh via trimesh boolean
ops on the same box dimensions already used for collision, not derived
from the real mesh in any way. Collision stays the plain convex box (see
URDF_TEMPLATE's own comment for why). Run generate_hole_peg_meshes.py
before this script.

Mesh paths ARE absolute again here (unlike the brief plain-box-only
version of this file), so the earlier "regenerate per environment"
caveat is back in play for these two objects too, same as the
UR10/Robotiq arm URDFs elsewhere in this directory.

Output is committed on this local-only branch for convenience, same as
everything else here — see ../README.md.
"""

from pathlib import Path

HERE = Path(__file__).parent
GEN_DIR = HERE / "generated"
# Run generate_hole_peg_meshes.py first — authored directly in meters
# (matching LEG_HALF_EXTENT/TABLE_HALF_EXTENT below), so no <mesh scale>
# is needed (avoids the pyhpp_viser bug documented in
# rescale_robotiq_meshes.py's / rescale_ikea_meshes.py's docstrings).
MESH_GENERATED_DIR = HERE / "assets" / "meshes_generated"

# (name, mesh file, world pos in the reference MJCF, half-extent collision
#  box, local-frame top connection-site z, local-frame corner half-extents)
LEG_HALF_EXTENT = (0.015, 0.015, 0.13125)
LEGS = [
    dict(name="leg1", mesh="leg1.stl"),
    dict(name="leg2", mesh="leg2.stl"),
    dict(name="leg3", mesh="leg3.stl"),
    dict(name="leg4", mesh="leg4.stl"),
]

TABLE_HALF_EXTENT = (0.32, 0.12, 0.02)
# Table-local XY positions of the 4 leg sockets (underside), from the
# reference MJCF's table-leg conn_site1..4 (z is the table's own -half_z).
LEG_SOCKET_XY = [
    (-0.305, -0.095),
    (-0.305, 0.095),
    (0.305, -0.095),
    (0.305, 0.095),
]

URDF_TEMPLATE = """<?xml version="1.0"?>
<!--
  GENERATED by script/ikea_table_prototype/generate_urdf_srdf.py — local
  prototype only, see script/ikea_table_prototype/README.md. Box
  dimensions read from the vendored reference MJCF (LACK table,
  originally from clvrai/furniture, itself real IKEA product geometry).

  Visual geometry is {visual_mesh_basename} — a fresh, programmatically
  generated box-with-holes/box-with-peg mesh (see
  generate_hole_peg_meshes.py; NOT the real vendored IKEA STL, which
  bakes in the actual product's screw-hole surface detail and wasn't
  wanted even for local prototyping). Collision stays the plain convex
  box below — HPP-FCL's narrow-phase checking wants convex shapes, and
  the hole/peg mesh isn't; visual/collision not matching exactly is
  standard practice (detailed visual mesh, simple convex collision
  proxy).
-->
<robot name="{name}">
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{visual_mesh_path}"/>
      </geometry>
      <material name="light_wood">
        <color rgba="0.82 0.71 0.55 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="{box_size}"/>
      </geometry>
    </collision>
  </link>
</robot>
"""

SRDF_LEG_TEMPLATE = """<?xml version="1.0"?>
<!-- GENERATED — see generate_urdf_srdf.py. Local prototype only. -->
<robot name="{name}">
  <!-- Grasp point: leg center, gripper approaches from the side (world -X
       in the leg's own frame at rest) — a parallel jaw closing across the
       leg's 0.03x0.03 cross-section. Tentative: verify/tune live against
       the actual Robotiq URDF once wired into a scene; the pokeball
       precedent this repo already has is a poor analog (sphere grasps are
       orientation-insensitive, a peg grasp is not). -->
  <handle name="{name}/handle" clearance="0.02" approaching_direction="1 0 0">
    <position xyz="0 0 0" xyzw="0 0 0 1"/>
    <link name="base_link"/>
  </handle>
  <!-- Placement contact: the leg's top face, mated against the matching
       socket contact on the table (see table.srdf) — same mechanism as
       script/twin/assets/pokeball_bimanual.srdf's "bottom" contact. -->
  <contact name="{name}/top">
    <link name="base_link"/>
    <point>
       {hx} {hy} {top_z}
      -{hx} {hy} {top_z}
      -{hx} -{hy} {top_z}
       {hx} -{hy} {top_z}
    </point>
    <shape>
      4 0 1 2 3
    </shape>
  </contact>
</robot>
"""

SRDF_TABLE_TEMPLATE = """<?xml version="1.0"?>
<!-- GENERATED — see generate_urdf_srdf.py. Local prototype only. -->
<robot name="table">
  <!-- Grasp point: top face center, in case a phase needs to hold the
       table steady while a leg is attached. Tentative, same caveat as
       the leg handles. -->
  <handle name="table/handle" clearance="0.02" approaching_direction="0 0 1">
    <position xyz="0 0 0" xyzw="0 0 0 1"/>
    <link name="base_link"/>
  </handle>
{contacts}</robot>
"""

SOCKET_CONTACT_TEMPLATE = """  <!-- Socket {i}: mates with legN/top, at table-local ({cx}, {cy}) -->
  <contact name="table/socket{i}">
    <link name="base_link"/>
    <point>
       {p0x} {p0y} {sock_z}
       {p1x} {p1y} {sock_z}
       {p2x} {p2y} {sock_z}
       {p3x} {p3y} {sock_z}
    </point>
    <shape>
      4 0 1 2 3
    </shape>
  </contact>
"""


def write(path: Path, content: str) -> None:
    path.write_text(content)
    print(f"wrote {path.relative_to(HERE.parent.parent)}")


def main() -> None:
    GEN_DIR.mkdir(exist_ok=True)

    leg_peg_mesh_path = str((MESH_GENERATED_DIR / "leg_with_peg.stl").resolve())
    table_holes_mesh_path = str(
        (MESH_GENERATED_DIR / "table_with_holes.stl").resolve()
    )

    lx, ly, lz = LEG_HALF_EXTENT
    leg_box_size = f"{2*lx} {2*ly} {2*lz}"
    leg_mass = "0.3"

    for leg in LEGS:
        name = leg["name"]
        urdf = URDF_TEMPLATE.format(
            name=name,
            mass=leg_mass,
            visual_mesh_basename="leg_with_peg.stl",
            visual_mesh_path=leg_peg_mesh_path,
            box_size=leg_box_size,
        )
        write(GEN_DIR / f"{name}.urdf", urdf)

        srdf = SRDF_LEG_TEMPLATE.format(
            name=name,
            hx=lx,
            hy=ly,
            top_z=round(lz, 6),
        )
        write(GEN_DIR / f"{name}.srdf", srdf)

    tx, ty, tz = TABLE_HALF_EXTENT
    table_box_size = f"{2*tx} {2*ty} {2*tz}"
    table_urdf = URDF_TEMPLATE.format(
        name="table",
        mass="2.0",
        visual_mesh_basename="table_with_holes.stl",
        visual_mesh_path=table_holes_mesh_path,
        box_size=table_box_size,
    )
    write(GEN_DIR / "table.urdf", table_urdf)

    sock_z = round(-tz, 6)
    contact_blocks = []
    for i, (cx, cy) in enumerate(LEG_SOCKET_XY, start=1):
        corners = [(cx + sx, cy + sy) for sx in (lx, -lx) for sy in (ly, -ly)]
        contact_blocks.append(
            SOCKET_CONTACT_TEMPLATE.format(
                i=i,
                cx=cx,
                cy=cy,
                sock_z=sock_z,
                p0x=corners[0][0], p0y=corners[0][1],
                p1x=corners[1][0], p1y=corners[1][1],
                p2x=corners[2][0], p2y=corners[2][1],
                p3x=corners[3][0], p3y=corners[3][1],
            )
        )
    table_srdf = SRDF_TABLE_TEMPLATE.format(contacts="".join(contact_blocks))
    write(GEN_DIR / "table.srdf", table_srdf)


if __name__ == "__main__":
    main()
