#!/usr/bin/env python3
"""Merge UR10 + Robotiq 2F-85 into one combined-arm URDF.

Local prototype only — see ../README.md. Neither source repo ships a
combined description (they're separate ROS packages, never composed
upstream), so this stitches them: takes every <link>/<joint> from both
generated URDFs, adds one new fixed joint mounting the gripper's root link
(robotiq_arg2f_base_link) onto the arm's tool0 frame.

Mount offset (xyz/rpy on the new fixed joint) — identity — and the TCP
frame's 0.15m z-offset were both visually verified in viser (see
view_arm_gripper.py): the gripper renders flush and correctly-oriented on
tool0, arm fully visible. That check needed a separate fix first — see
rescale_robotiq_meshes.py's docstring for a real pyhpp_viser rendering bug
this ran into along the way (non-unit <mesh scale> collapses geometry
toward world origin).

Generates TWO files: ur10_robotiq.urdf (identity world placement, for
ur10_left) and ur10_robotiq_right.urdf (world offset baked in via an outer
"world_mount" fixed link, for ur10_right). The offset is baked into the
URDF itself rather than applied via PyHPPBackend.load_robot(pose=...) /
Device.setRobotRootPosition() after loading — found a real pyhpp_viser bug
where that post-load repositioning isn't reflected in *static* (fixed-to-
universe) geometry rendering: ur10_right's pedestal rendered at ur10_left's
position (both cached [0,0,0.15]) even though the real FK/model data was
already correct (confirmed via direct Pinocchio queries before concluding
this was a viewer bug, not a modeling one) — only geometry driven by a real
moving joint reflected the offset correctly. Baking the offset into the
URDF's own static structure instead sidesteps that code path entirely,
matching how ur10_left (loaded at identity, i.e. no post-load reposition)
already rendered correctly from the start.
"""

import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent
UR10_URDF = HERE / "assets" / "ur10" / "ur10_robot_generated.urdf"
ROBOTIQ_URDF = HERE / "assets" / "robotiq_2f85" / "urdf" / "robotiq_2f85_generated.urdf"

GRIPPER_ROOT_LINK = "robotiq_arg2f_base_link"
ARM_MOUNT_FRAME = "tool0"

# Pedestal: a rigid part of this same URDF (fixed joint onto UR10's own
# root link, "world"), not a separately-positioned environment object —
# per live feedback that two independently-placed objects read as a gap
# rather than one attached assembly. 0.3m tall (lowered from an initial
# 0.5m guess, also per feedback), 0.3x0.3m footprint.
PEDESTAL_LINK = "pedestal"
PEDESTAL_HEIGHT = 0.3
UR10_ROOT_LINK = "world"

# Mount transform — identity, visually verified in viser. See docstring.
MOUNT_XYZ = "0 0 0"
MOUNT_RPY = "0 0 0"

# TCP frame: base_link's own +Z is the fingers' approach direction (verified
# from the joint chain: finger_joint at z=0.0549, + left_inner_finger_joint
# at z=0.0471 more = ~0.102m to the inner-finger pivot; fingertip contact is
# further out). 0.15m is a published-typical 2F-85 TCP estimate, visually
# verified (arm+gripper render correctly in viser) but not measured against
# this exact mesh — fine for prototyping, revisit before anything precision-
# sensitive (e.g. actual grasp-pose tuning) depends on it.
TCP_LINK = "gripper_tcp"
TCP_Z = "0.15"

WORLD_MOUNT_LINK = "world_mount"
# ur10_right's world placement — 1.5m along X, rotated 180deg about Z to
# face back toward ur10_left. Matches view_full_scene.py's layout.
RIGHT_ARM_XYZ = "1.5 0 0"
RIGHT_ARM_RPY = "0 0 3.141592653589793"


def build(world_xyz: str | None, world_rpy: str | None) -> ET.Element:
    ur10_tree = ET.parse(UR10_URDF)
    ur10_root = ur10_tree.getroot()

    robotiq_tree = ET.parse(ROBOTIQ_URDF)
    robotiq_root = robotiq_tree.getroot()

    combined = ET.Element("robot", {"name": "ur10_robotiq"})
    combined.append(
        ET.Comment(
            " GENERATED by merge_ur10_robotiq.py — local prototype only. "
            "UR10 (Gepetto/example-robot-data, BSD-3-Clause) + Robotiq "
            "2F-85 (ros-industrial/robotiq, BSD-2-Clause), stitched at "
            "tool0. Mount offset + TCP frame visually verified in viser "
            "— see module docstring. "
        )
    )

    for child in ur10_root:
        if child.tag in ("link", "joint"):
            combined.append(child)
    for child in robotiq_root:
        if child.tag in ("link", "joint"):
            combined.append(child)

    pedestal_link = ET.Element("link", {"name": PEDESTAL_LINK})
    visual = ET.SubElement(pedestal_link, "visual")
    ET.SubElement(visual, "origin", {"xyz": f"0 0 {PEDESTAL_HEIGHT / 2}"})
    geom = ET.SubElement(visual, "geometry")
    ET.SubElement(geom, "box", {"size": f"0.3 0.3 {PEDESTAL_HEIGHT}"})
    material = ET.SubElement(visual, "material", {"name": "DarkGray"})
    ET.SubElement(material, "color", {"rgba": "0.3 0.3 0.3 1.0"})
    collision = ET.SubElement(pedestal_link, "collision")
    ET.SubElement(collision, "origin", {"xyz": f"0 0 {PEDESTAL_HEIGHT / 2}"})
    geom = ET.SubElement(collision, "geometry")
    ET.SubElement(geom, "box", {"size": f"0.3 0.3 {PEDESTAL_HEIGHT}"})
    combined.append(pedestal_link)

    pedestal_joint = ET.Element(
        "joint", {"name": "pedestal_to_arm", "type": "fixed"}
    )
    ET.SubElement(
        pedestal_joint, "origin", {"xyz": f"0 0 {PEDESTAL_HEIGHT}", "rpy": "0 0 0"}
    )
    ET.SubElement(pedestal_joint, "parent", {"link": PEDESTAL_LINK})
    ET.SubElement(pedestal_joint, "child", {"link": UR10_ROOT_LINK})
    combined.append(pedestal_joint)

    mount_joint = ET.Element(
        "joint", {"name": "tool0_to_gripper", "type": "fixed"}
    )
    ET.SubElement(mount_joint, "origin", {"xyz": MOUNT_XYZ, "rpy": MOUNT_RPY})
    ET.SubElement(mount_joint, "parent", {"link": ARM_MOUNT_FRAME})
    ET.SubElement(mount_joint, "child", {"link": GRIPPER_ROOT_LINK})
    combined.append(mount_joint)

    tcp_link = ET.Element("link", {"name": TCP_LINK})
    combined.append(tcp_link)
    tcp_joint = ET.Element("joint", {"name": "gripper_to_tcp", "type": "fixed"})
    ET.SubElement(tcp_joint, "origin", {"xyz": f"0 0 {TCP_Z}", "rpy": "0 0 0"})
    ET.SubElement(tcp_joint, "parent", {"link": GRIPPER_ROOT_LINK})
    ET.SubElement(tcp_joint, "child", {"link": TCP_LINK})
    combined.append(tcp_joint)

    if world_xyz is not None:
        world_mount_link = ET.Element("link", {"name": WORLD_MOUNT_LINK})
        combined.append(world_mount_link)
        world_mount_joint = ET.Element(
            "joint", {"name": "world_mount_to_pedestal", "type": "fixed"}
        )
        ET.SubElement(
            world_mount_joint, "origin", {"xyz": world_xyz, "rpy": world_rpy}
        )
        ET.SubElement(world_mount_joint, "parent", {"link": WORLD_MOUNT_LINK})
        ET.SubElement(world_mount_joint, "child", {"link": PEDESTAL_LINK})
        combined.append(world_mount_joint)

    return combined


def write(root: ET.Element, out_path: Path) -> None:
    out_path.parent.mkdir(exist_ok=True)
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(out_path, xml_declaration=True, encoding="unicode")
    print(f"wrote {out_path.relative_to(HERE.parent.parent)}")


def main() -> None:
    write(build(None, None), HERE / "generated" / "ur10_robotiq.urdf")
    write(
        build(RIGHT_ARM_XYZ, RIGHT_ARM_RPY),
        HERE / "generated" / "ur10_robotiq_right.urdf",
    )


if __name__ == "__main__":
    main()
